### ISSUE TITLE
Descendents for selected IDs are not shown.

### ISSUE THREAD

**Issue by b-gehrke** [jannahastings/onto-vis#5]
For example, `BCIO:011059|interactional mode of delivery` shows not all descendants.

**Comment by b-gehrke** [comment]
@jannahastings What would you expect to see in the visualization for the ID `BCIO:011059`? The class has no direct or indirect subclasses.

**Comment by jannahastings** [comment]
Ah, okay, sorry, then this was my mistake -- I thought it should have `human interactional mode of delivery` as a subclass, but in fact this isn't the case.
